// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/harness.dart';
import 'api/memory.dart';
import 'api/sandbox.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DecisionAction dco_decode_decision_action(dynamic raw);

  @protected
  EvalReport dco_decode_eval_report(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<MemoryEntry> dco_decode_list_memory_entry(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SkillDesc> dco_decode_list_skill_desc(dynamic raw);

  @protected
  MemoryEntry dco_decode_memory_entry(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  ParsedKind dco_decode_parsed_kind(dynamic raw);

  @protected
  ParsedOutput dco_decode_parsed_output(dynamic raw);

  @protected
  SkillDesc dco_decode_skill_desc(dynamic raw);

  @protected
  StepDecision dco_decode_step_decision(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DecisionAction sse_decode_decision_action(SseDeserializer deserializer);

  @protected
  EvalReport sse_decode_eval_report(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<MemoryEntry> sse_decode_list_memory_entry(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SkillDesc> sse_decode_list_skill_desc(SseDeserializer deserializer);

  @protected
  MemoryEntry sse_decode_memory_entry(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  ParsedKind sse_decode_parsed_kind(SseDeserializer deserializer);

  @protected
  ParsedOutput sse_decode_parsed_output(SseDeserializer deserializer);

  @protected
  SkillDesc sse_decode_skill_desc(SseDeserializer deserializer);

  @protected
  StepDecision sse_decode_step_decision(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_decision_action(
    DecisionAction self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_eval_report(EvalReport self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_memory_entry(
    List<MemoryEntry> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_skill_desc(
    List<SkillDesc> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_memory_entry(MemoryEntry self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_parsed_kind(ParsedKind self, SseSerializer serializer);

  @protected
  void sse_encode_parsed_output(ParsedOutput self, SseSerializer serializer);

  @protected
  void sse_encode_skill_desc(SkillDesc self, SseSerializer serializer);

  @protected
  void sse_encode_step_decision(StepDecision self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
