// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/harness.dart';
import 'api/memory.dart';
import 'api/sandbox.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -37313148;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_wranglv0',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  StepDecision crateApiHarnessDecideNext({
    required String rawModelOutput,
    required List<String> validTools,
    required List<String> prevAssistantOutputs,
    required int retriesSoFar,
    required int maxRetries,
  });

  EvalReport crateApiHarnessEvaluate({
    required String outputRaw,
    required List<String> validTools,
    required List<String> prevAssistantOutputs,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  void crateApiMemoryMemoryAppend({
    required String path,
    required String task,
    required String result,
    required int maxEntries,
    required int summaryChars,
  });

  List<MemoryEntry> crateApiMemoryMemoryLoad({required String path});

  String crateApiMemoryMemoryRender({required List<MemoryEntry> entries});

  ParsedOutput crateApiHarnessParseOutput({required String raw});

  String crateApiHarnessRouteSkill({
    required String task,
    required List<SkillDesc> skills,
  });

  String crateApiSandboxTruncateToolText({
    required String text,
    required int maxChars,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  StepDecision crateApiHarnessDecideNext({
    required String rawModelOutput,
    required List<String> validTools,
    required List<String> prevAssistantOutputs,
    required int retriesSoFar,
    required int maxRetries,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(rawModelOutput, serializer);
          sse_encode_list_String(validTools, serializer);
          sse_encode_list_String(prevAssistantOutputs, serializer);
          sse_encode_u_32(retriesSoFar, serializer);
          sse_encode_u_32(maxRetries, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_step_decision,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHarnessDecideNextConstMeta,
        argValues: [
          rawModelOutput,
          validTools,
          prevAssistantOutputs,
          retriesSoFar,
          maxRetries,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHarnessDecideNextConstMeta => const TaskConstMeta(
    debugName: "decide_next",
    argNames: [
      "rawModelOutput",
      "validTools",
      "prevAssistantOutputs",
      "retriesSoFar",
      "maxRetries",
    ],
  );

  @override
  EvalReport crateApiHarnessEvaluate({
    required String outputRaw,
    required List<String> validTools,
    required List<String> prevAssistantOutputs,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(outputRaw, serializer);
          sse_encode_list_String(validTools, serializer);
          sse_encode_list_String(prevAssistantOutputs, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_eval_report,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHarnessEvaluateConstMeta,
        argValues: [outputRaw, validTools, prevAssistantOutputs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHarnessEvaluateConstMeta => const TaskConstMeta(
    debugName: "evaluate",
    argNames: ["outputRaw", "validTools", "prevAssistantOutputs"],
  );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  void crateApiMemoryMemoryAppend({
    required String path,
    required String task,
    required String result,
    required int maxEntries,
    required int summaryChars,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          sse_encode_String(task, serializer);
          sse_encode_String(result, serializer);
          sse_encode_u_32(maxEntries, serializer);
          sse_encode_u_32(summaryChars, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMemoryMemoryAppendConstMeta,
        argValues: [path, task, result, maxEntries, summaryChars],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryMemoryAppendConstMeta => const TaskConstMeta(
    debugName: "memory_append",
    argNames: ["path", "task", "result", "maxEntries", "summaryChars"],
  );

  @override
  List<MemoryEntry> crateApiMemoryMemoryLoad({required String path}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(path, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_memory_entry,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMemoryMemoryLoadConstMeta,
        argValues: [path],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryMemoryLoadConstMeta =>
      const TaskConstMeta(debugName: "memory_load", argNames: ["path"]);

  @override
  String crateApiMemoryMemoryRender({required List<MemoryEntry> entries}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_memory_entry(entries, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiMemoryMemoryRenderConstMeta,
        argValues: [entries],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiMemoryMemoryRenderConstMeta =>
      const TaskConstMeta(debugName: "memory_render", argNames: ["entries"]);

  @override
  ParsedOutput crateApiHarnessParseOutput({required String raw}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(raw, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_parsed_output,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHarnessParseOutputConstMeta,
        argValues: [raw],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHarnessParseOutputConstMeta =>
      const TaskConstMeta(debugName: "parse_output", argNames: ["raw"]);

  @override
  String crateApiHarnessRouteSkill({
    required String task,
    required List<SkillDesc> skills,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(task, serializer);
          sse_encode_list_skill_desc(skills, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiHarnessRouteSkillConstMeta,
        argValues: [task, skills],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiHarnessRouteSkillConstMeta => const TaskConstMeta(
    debugName: "route_skill",
    argNames: ["task", "skills"],
  );

  @override
  String crateApiSandboxTruncateToolText({
    required String text,
    required int maxChars,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(text, serializer);
          sse_encode_u_32(maxChars, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSandboxTruncateToolTextConstMeta,
        argValues: [text, maxChars],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSandboxTruncateToolTextConstMeta =>
      const TaskConstMeta(
        debugName: "truncate_tool_text",
        argNames: ["text", "maxChars"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DecisionAction dco_decode_decision_action(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DecisionAction.values[raw as int];
  }

  @protected
  EvalReport dco_decode_eval_report(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return EvalReport(
      passed: dco_decode_bool(arr[0]),
      score: dco_decode_f_32(arr[1]),
      reason: dco_decode_String(arr[2]),
      retryPrompt: dco_decode_String(arr[3]),
    );
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<MemoryEntry> dco_decode_list_memory_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_memory_entry).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<SkillDesc> dco_decode_list_skill_desc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_skill_desc).toList();
  }

  @protected
  MemoryEntry dco_decode_memory_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return MemoryEntry(
      task: dco_decode_String(arr[0]),
      result: dco_decode_String(arr[1]),
    );
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  ParsedKind dco_decode_parsed_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ParsedKind.values[raw as int];
  }

  @protected
  ParsedOutput dco_decode_parsed_output(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ParsedOutput(
      kind: dco_decode_parsed_kind(arr[0]),
      tool: dco_decode_opt_String(arr[1]),
      argsJson: dco_decode_opt_String(arr[2]),
      content: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  SkillDesc dco_decode_skill_desc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return SkillDesc(
      name: dco_decode_String(arr[0]),
      description: dco_decode_String(arr[1]),
    );
  }

  @protected
  StepDecision dco_decode_step_decision(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return StepDecision(
      action: dco_decode_decision_action(arr[0]),
      toolName: dco_decode_opt_String(arr[1]),
      toolArgsJson: dco_decode_opt_String(arr[2]),
      finalText: dco_decode_opt_String(arr[3]),
      retryFeedback: dco_decode_opt_String(arr[4]),
      newAssistantLog: dco_decode_String(arr[5]),
      retriesAfter: dco_decode_u_32(arr[6]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DecisionAction sse_decode_decision_action(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DecisionAction.values[inner];
  }

  @protected
  EvalReport sse_decode_eval_report(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_passed = sse_decode_bool(deserializer);
    var var_score = sse_decode_f_32(deserializer);
    var var_reason = sse_decode_String(deserializer);
    var var_retryPrompt = sse_decode_String(deserializer);
    return EvalReport(
      passed: var_passed,
      score: var_score,
      reason: var_reason,
      retryPrompt: var_retryPrompt,
    );
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<MemoryEntry> sse_decode_list_memory_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <MemoryEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_memory_entry(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<SkillDesc> sse_decode_list_skill_desc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SkillDesc>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_skill_desc(deserializer));
    }
    return ans_;
  }

  @protected
  MemoryEntry sse_decode_memory_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_task = sse_decode_String(deserializer);
    var var_result = sse_decode_String(deserializer);
    return MemoryEntry(task: var_task, result: var_result);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ParsedKind sse_decode_parsed_kind(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ParsedKind.values[inner];
  }

  @protected
  ParsedOutput sse_decode_parsed_output(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_parsed_kind(deserializer);
    var var_tool = sse_decode_opt_String(deserializer);
    var var_argsJson = sse_decode_opt_String(deserializer);
    var var_content = sse_decode_opt_String(deserializer);
    return ParsedOutput(
      kind: var_kind,
      tool: var_tool,
      argsJson: var_argsJson,
      content: var_content,
    );
  }

  @protected
  SkillDesc sse_decode_skill_desc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_description = sse_decode_String(deserializer);
    return SkillDesc(name: var_name, description: var_description);
  }

  @protected
  StepDecision sse_decode_step_decision(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_action = sse_decode_decision_action(deserializer);
    var var_toolName = sse_decode_opt_String(deserializer);
    var var_toolArgsJson = sse_decode_opt_String(deserializer);
    var var_finalText = sse_decode_opt_String(deserializer);
    var var_retryFeedback = sse_decode_opt_String(deserializer);
    var var_newAssistantLog = sse_decode_String(deserializer);
    var var_retriesAfter = sse_decode_u_32(deserializer);
    return StepDecision(
      action: var_action,
      toolName: var_toolName,
      toolArgsJson: var_toolArgsJson,
      finalText: var_finalText,
      retryFeedback: var_retryFeedback,
      newAssistantLog: var_newAssistantLog,
      retriesAfter: var_retriesAfter,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_decision_action(
    DecisionAction self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_eval_report(EvalReport self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.passed, serializer);
    sse_encode_f_32(self.score, serializer);
    sse_encode_String(self.reason, serializer);
    sse_encode_String(self.retryPrompt, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_memory_entry(
    List<MemoryEntry> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_memory_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_skill_desc(
    List<SkillDesc> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_skill_desc(item, serializer);
    }
  }

  @protected
  void sse_encode_memory_entry(MemoryEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.task, serializer);
    sse_encode_String(self.result, serializer);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_parsed_kind(ParsedKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_parsed_output(ParsedOutput self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_parsed_kind(self.kind, serializer);
    sse_encode_opt_String(self.tool, serializer);
    sse_encode_opt_String(self.argsJson, serializer);
    sse_encode_opt_String(self.content, serializer);
  }

  @protected
  void sse_encode_skill_desc(SkillDesc self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.description, serializer);
  }

  @protected
  void sse_encode_step_decision(StepDecision self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_decision_action(self.action, serializer);
    sse_encode_opt_String(self.toolName, serializer);
    sse_encode_opt_String(self.toolArgsJson, serializer);
    sse_encode_opt_String(self.finalText, serializer);
    sse_encode_opt_String(self.retryFeedback, serializer);
    sse_encode_String(self.newAssistantLog, serializer);
    sse_encode_u_32(self.retriesAfter, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
