// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clean`, `extract_object_field`, `extract_string_field`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `eq`, `fmt`

/// Defensively parse one model turn into a tool call or a final answer.
///
/// Order of preference: an explicit `"tool"` field → tool call; a `"answer"`
/// or `"result"` field → final answer; otherwise the whole cleaned text is
/// treated as the final answer (lightweight models often skip the wrapper).
ParsedOutput parseOutput({required String raw}) =>
    RustLib.instance.api.crateApiHarnessParseOutput(raw: raw);

/// Run the standing guardrails against a single model turn.
///
/// - `output_raw`: the current model output.
/// - `valid_tools`: the scoped tool names for the active skill.
/// - `prev_assistant_outputs`: prior assistant turns (NOT including current),
///   used to detect the model getting stuck repeating itself.
EvalReport evaluate({
  required String outputRaw,
  required List<String> validTools,
  required List<String> prevAssistantOutputs,
}) => RustLib.instance.api.crateApiHarnessEvaluate(
  outputRaw: outputRaw,
  validTools: validTools,
  prevAssistantOutputs: prevAssistantOutputs,
);

/// Deterministic fast-path router. Returns the matched skill name, or "none"
/// to signal that Dart should fall back to an LLM routing call.
///
/// Only ever returns a skill that is actually present in `skills`.
String routeSkill({required String task, required List<SkillDesc> skills}) =>
    RustLib.instance.api.crateApiHarnessRouteSkill(task: task, skills: skills);

/// Aggregated verdict over all guardrail checks for one model turn.
class EvalReport {
  final bool passed;
  final double score;
  final String reason;

  /// A prompt to feed back to the model on failure (empty when passed).
  final String retryPrompt;

  const EvalReport({
    required this.passed,
    required this.score,
    required this.reason,
    required this.retryPrompt,
  });

  @override
  int get hashCode =>
      passed.hashCode ^ score.hashCode ^ reason.hashCode ^ retryPrompt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EvalReport &&
          runtimeType == other.runtimeType &&
          passed == other.passed &&
          score == other.score &&
          reason == other.reason &&
          retryPrompt == other.retryPrompt;
}

enum ParsedKind { toolCall, finalAnswer }

/// The result of defensively parsing one model turn.
///
/// `args_json` is returned as a raw JSON substring; Dart decodes it with its
/// built-in `jsonDecode`, so Rust never needs a JSON dependency.
class ParsedOutput {
  final ParsedKind kind;
  final String? tool;
  final String? argsJson;
  final String? content;

  const ParsedOutput({
    required this.kind,
    this.tool,
    this.argsJson,
    this.content,
  });

  @override
  int get hashCode =>
      kind.hashCode ^ tool.hashCode ^ argsJson.hashCode ^ content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ParsedOutput &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          tool == other.tool &&
          argsJson == other.argsJson &&
          content == other.content;
}

class SkillDesc {
  final String name;
  final String description;

  const SkillDesc({required this.name, required this.description});

  @override
  int get hashCode => name.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SkillDesc &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description;
}
