// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_line`, `tail_chars`, `write_all`

/// Load every entry from `path`. Missing or unreadable files yield an empty
/// list — corrupted memory is never fatal.
List<MemoryEntry> memoryLoad({required String path}) =>
    RustLib.instance.api.crateApiMemoryMemoryLoad(path: path);

/// Append one entry, truncate `result` to the last `summary_chars`, and
/// rewrite the file so it holds at most `max_entries` lines (oldest dropped).
/// Errors are swallowed — memory is best-effort and must not crash the loop.
void memoryAppend({
  required String path,
  required String task,
  required String result,
  required int maxEntries,
  required int summaryChars,
}) => RustLib.instance.api.crateApiMemoryMemoryAppend(
  path: path,
  task: task,
  result: result,
  maxEntries: maxEntries,
  summaryChars: summaryChars,
);

/// Render entries for injection into a system prompt. Returns an empty string
/// when there are no entries so the caller can skip the "Relevant memory:"
/// section entirely.
String memoryRender({required List<MemoryEntry> entries}) =>
    RustLib.instance.api.crateApiMemoryMemoryRender(entries: entries);

class MemoryEntry {
  final String task;
  final String result;

  const MemoryEntry({required this.task, required this.result});

  @override
  int get hashCode => task.hashCode ^ result.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MemoryEntry &&
          runtimeType == other.runtimeType &&
          task == other.task &&
          result == other.result;
}
