// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Cap text-tool output at `max_chars`. Tool results that exceed the cap are
/// truncated to keep the conversation history bounded — same rule the
/// agent-harness skill calls out (<= 500 chars before re-entering the loop).
String truncateToolText({required String text, required int maxChars}) =>
    RustLib.instance.api.crateApiSandboxTruncateToolText(
      text: text,
      maxChars: maxChars,
    );
